package com.worldsnas.domain.repomodel

data class MovieRepoModel(
    val id: Long = 0,
    val adult: Boolean = false,
    val backdropPath: String = "",
    val budget: Long = 0,
    val genres: List<GenreRepoModel> = emptyList(),
    val homePage: String = "",
    val imdbID: String = "",
    val originalLanguage: String = "",
    val originalTitle: String = "",
    val overview: String = "",
    val popularity: Double = 0.0,
    val posterPath: String = "",
    val productionCompanies: List<CompanyRepoModel> = emptyList(),
    val productionCountries: List<CountryRepoModel> = emptyList(),
    val releaseDate: String = "",
    val revenue: Long = 0,
    val runtime: Int = 0,
    val spokenLanguages: List<LanguageRepoModel> = emptyList(),
    val status: String = "",
    val tagLine: String = "",
    val title: String = "",
    val video: Boolean = false,
    val voteAverage: Double = 0.0,
    val voteCount: Int = 0,
    val videos: List<VideoRepoModel>,
    val backdrops: List<ImageRepoModel> = emptyList(),
    val posters: List<ImageRepoModel> = emptyList(),
    val reviews: List<ReviewRepoModel> = emptyList(),
    val similar: List<MovieRepoModel> = emptyList(),
    val recommendations: List<MovieRepoModel> = emptyList(),
    val casts: List<CastRepoModel> = emptyList(),
    val crews: List<CrewRepoModel> = emptyList(),
    val translations: List<TranslationRepoModel> = emptyList(),
    val facebookId: String = "",
    val instagramId: String = "",
    val twitterId: String = ""
)
